name: Rust Test

on:
  pull_request:
    branches: [ main ]  # or the default branch of your repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can specify other OSes as well

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal  # Only install the essential components
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --nocapture  # '-- --nocapture' is optional

